"""add baseline weight

Revision ID: 0c80048cf9fb
Revises: 4eb4810800df
Create Date: 2026-03-02 10:08:02.672611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c80048cf9fb'
down_revision = '4eb4810800df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline', sa.Boolean(), nullable=False))

    with op.batch_alter_table('weight_log_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline', sa.Boolean(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_log_version', schema=None) as batch_op:
        batch_op.drop_column('baseline')

    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.drop_column('baseline')

    # ### end Alembic commands ###
