"""Add user role and transaction tracking

Revision ID: 1e39d2125c99
Revises: dffc8dfc47e1
Create Date: 2026-02-25 09:31:21.422618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e39d2125c99'
down_revision = 'dffc8dfc47e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_event_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('procedure_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('procedure_target_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('completion_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_animal_event_version'))
    )
    with op.batch_alter_table('animal_event_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_event_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_event_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_event_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_event_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_event_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_procedure_target_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_animal_procedure_target_version'))
    )
    with op.batch_alter_table('animal_procedure_target_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_procedure_target_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_procedure_target_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_procedure_target_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_procedure_target_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_procedure_target_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_procedure_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_animal_procedure_version'))
    )
    with op.batch_alter_table('animal_procedure_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_procedure_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_procedure_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_procedure_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_procedure_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_procedure_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('custom_id', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('cage_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('species_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('dob', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('breeding_pair_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('termination_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('termination_reason_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_animal_version'))
    )
    with op.batch_alter_table('animal_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('breeding_pair_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('custom_id', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('male_animal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('female_animal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_breeding_pair_version'))
    )
    with op.batch_alter_table('breeding_pair_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_pair_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_pair_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_breeding_pair_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_breeding_pair_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_pair_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('cage_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('custom_id', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('species_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_cage_version'))
    )
    with op.batch_alter_table('cage_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cage_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cage_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_cage_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_cage_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cage_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('confocal_image_type_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_confocal_image_type_version'))
    )
    with op.batch_alter_table('confocal_image_type_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confocal_image_type_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confocal_image_type_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_confocal_image_type_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_confocal_image_type_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confocal_image_type_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('confocal_image_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ear_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('image_type_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_confocal_image_version'))
    )
    with op.batch_alter_table('confocal_image_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confocal_image_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confocal_image_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_confocal_image_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_confocal_image_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confocal_image_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('ear_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('side', sa.String(length=5), autoincrement=False, nullable=True),
    sa.Column('cryoprotection_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('dissection_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('immunolabel_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('panel_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_ear_version'))
    )
    with op.batch_alter_table('ear_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ear_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ear_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_ear_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_ear_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ear_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('immunolabeling_panel_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_immunolabeling_panel_version'))
    )
    with op.batch_alter_table('immunolabeling_panel_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immunolabeling_panel_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_immunolabeling_panel_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_immunolabeling_panel_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_immunolabeling_panel_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_immunolabeling_panel_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('litter_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('breeding_pair_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('pup_count', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('wean_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_litter_version'))
    )
    with op.batch_alter_table('litter_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litter_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_litter_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_litter_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_litter_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_litter_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('reagent_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('panel_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_reagent_version'))
    )
    with op.batch_alter_table('reagent_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reagent_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reagent_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_reagent_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_reagent_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reagent_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('source_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_source_version'))
    )
    with op.batch_alter_table('source_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_source_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_source_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('species_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_species_version'))
    )
    with op.batch_alter_table('species_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_species_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_species_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_species_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_species_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_species_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('study_animals_version',
    sa.Column('study_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('study_id', 'animal_id', 'transaction_id', name=op.f('pk_study_animals_version'))
    )
    with op.batch_alter_table('study_animals_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_animals_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_animals_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_study_animals_version_pk_transaction_id', ['study_id', 'animal_id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_study_animals_version_pk_validity', ['study_id', 'animal_id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_animals_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('study_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_study_version'))
    )
    with op.batch_alter_table('study_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_study_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_study_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('termination_reason_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_termination_reason_version'))
    )
    with op.batch_alter_table('termination_reason_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_termination_reason_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termination_reason_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_termination_reason_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_termination_reason_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_termination_reason_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('name', name=op.f('uq_user_role_name'))
    )
    op.create_table('user_role_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_user_role_version'))
    )
    with op.batch_alter_table('user_role_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_user_role_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_user_role_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('user_roles_version',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'transaction_id', name=op.f('pk_user_roles_version'))
    )
    with op.batch_alter_table('user_roles_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_user_roles_version_pk_transaction_id', ['user_id', 'role_id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_user_roles_version_pk_validity', ['user_id', 'role_id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('user_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.String(length=128), autoincrement=False, nullable=True),
    sa.Column('active', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_user_version'))
    )
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_user_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_user_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_transaction_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], name=op.f('fk_user_roles_role_id_user_role')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_roles_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('animal_event', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('animal_procedure', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('animal_procedure_target', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('breeding_pair', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cage', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('confocal_image', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('confocal_image_type', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('ear', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('immunolabeling_panel', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('reagent', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('termination_reason', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termination_reason', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('reagent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('immunolabeling_panel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('ear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('confocal_image_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('confocal_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('cage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('breeding_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('animal_procedure_target', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('animal_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('animal_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    op.drop_table('user_roles')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_version_transaction_id'))
        batch_op.drop_index('ix_user_version_pk_validity')
        batch_op.drop_index('ix_user_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_user_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_user_version_end_transaction_id'))

    op.drop_table('user_version')
    with op.batch_alter_table('user_roles_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_version_transaction_id'))
        batch_op.drop_index('ix_user_roles_version_pk_validity')
        batch_op.drop_index('ix_user_roles_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_user_roles_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_user_roles_version_end_transaction_id'))

    op.drop_table('user_roles_version')
    with op.batch_alter_table('user_role_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_version_transaction_id'))
        batch_op.drop_index('ix_user_role_version_pk_validity')
        batch_op.drop_index('ix_user_role_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_user_role_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_user_role_version_end_transaction_id'))

    op.drop_table('user_role_version')
    op.drop_table('user_role')
    op.drop_table('user')
    with op.batch_alter_table('termination_reason_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_termination_reason_version_transaction_id'))
        batch_op.drop_index('ix_termination_reason_version_pk_validity')
        batch_op.drop_index('ix_termination_reason_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_termination_reason_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_termination_reason_version_end_transaction_id'))

    op.drop_table('termination_reason_version')
    with op.batch_alter_table('study_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_version_transaction_id'))
        batch_op.drop_index('ix_study_version_pk_validity')
        batch_op.drop_index('ix_study_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_study_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_study_version_end_transaction_id'))

    op.drop_table('study_version')
    with op.batch_alter_table('study_animals_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_animals_version_transaction_id'))
        batch_op.drop_index('ix_study_animals_version_pk_validity')
        batch_op.drop_index('ix_study_animals_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_study_animals_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_study_animals_version_end_transaction_id'))

    op.drop_table('study_animals_version')
    with op.batch_alter_table('species_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_species_version_transaction_id'))
        batch_op.drop_index('ix_species_version_pk_validity')
        batch_op.drop_index('ix_species_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_species_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_species_version_end_transaction_id'))

    op.drop_table('species_version')
    with op.batch_alter_table('source_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_version_transaction_id'))
        batch_op.drop_index('ix_source_version_pk_validity')
        batch_op.drop_index('ix_source_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_source_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_source_version_end_transaction_id'))

    op.drop_table('source_version')
    with op.batch_alter_table('reagent_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reagent_version_transaction_id'))
        batch_op.drop_index('ix_reagent_version_pk_validity')
        batch_op.drop_index('ix_reagent_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_reagent_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_reagent_version_end_transaction_id'))

    op.drop_table('reagent_version')
    with op.batch_alter_table('litter_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litter_version_transaction_id'))
        batch_op.drop_index('ix_litter_version_pk_validity')
        batch_op.drop_index('ix_litter_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_litter_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_litter_version_end_transaction_id'))

    op.drop_table('litter_version')
    with op.batch_alter_table('immunolabeling_panel_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immunolabeling_panel_version_transaction_id'))
        batch_op.drop_index('ix_immunolabeling_panel_version_pk_validity')
        batch_op.drop_index('ix_immunolabeling_panel_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_immunolabeling_panel_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_immunolabeling_panel_version_end_transaction_id'))

    op.drop_table('immunolabeling_panel_version')
    with op.batch_alter_table('ear_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ear_version_transaction_id'))
        batch_op.drop_index('ix_ear_version_pk_validity')
        batch_op.drop_index('ix_ear_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_ear_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_ear_version_end_transaction_id'))

    op.drop_table('ear_version')
    with op.batch_alter_table('confocal_image_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confocal_image_version_transaction_id'))
        batch_op.drop_index('ix_confocal_image_version_pk_validity')
        batch_op.drop_index('ix_confocal_image_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_confocal_image_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_confocal_image_version_end_transaction_id'))

    op.drop_table('confocal_image_version')
    with op.batch_alter_table('confocal_image_type_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confocal_image_type_version_transaction_id'))
        batch_op.drop_index('ix_confocal_image_type_version_pk_validity')
        batch_op.drop_index('ix_confocal_image_type_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_confocal_image_type_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_confocal_image_type_version_end_transaction_id'))

    op.drop_table('confocal_image_type_version')
    with op.batch_alter_table('cage_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cage_version_transaction_id'))
        batch_op.drop_index('ix_cage_version_pk_validity')
        batch_op.drop_index('ix_cage_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_cage_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_cage_version_end_transaction_id'))

    op.drop_table('cage_version')
    with op.batch_alter_table('breeding_pair_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_pair_version_transaction_id'))
        batch_op.drop_index('ix_breeding_pair_version_pk_validity')
        batch_op.drop_index('ix_breeding_pair_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_breeding_pair_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_breeding_pair_version_end_transaction_id'))

    op.drop_table('breeding_pair_version')
    with op.batch_alter_table('animal_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_version_transaction_id'))
        batch_op.drop_index('ix_animal_version_pk_validity')
        batch_op.drop_index('ix_animal_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_version_end_transaction_id'))

    op.drop_table('animal_version')
    with op.batch_alter_table('animal_procedure_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_procedure_version_transaction_id'))
        batch_op.drop_index('ix_animal_procedure_version_pk_validity')
        batch_op.drop_index('ix_animal_procedure_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_procedure_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_procedure_version_end_transaction_id'))

    op.drop_table('animal_procedure_version')
    with op.batch_alter_table('animal_procedure_target_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_procedure_target_version_transaction_id'))
        batch_op.drop_index('ix_animal_procedure_target_version_pk_validity')
        batch_op.drop_index('ix_animal_procedure_target_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_procedure_target_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_procedure_target_version_end_transaction_id'))

    op.drop_table('animal_procedure_target_version')
    with op.batch_alter_table('animal_event_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_event_version_transaction_id'))
        batch_op.drop_index('ix_animal_event_version_pk_validity')
        batch_op.drop_index('ix_animal_event_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_event_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_event_version_end_transaction_id'))

    op.drop_table('animal_event_version')
    # ### end Alembic commands ###
