"""Add default procedure target for DataType

Revision ID: 2a5b1dffef02
Revises: 6932f1d694cc
Create Date: 2026-04-15 20:37:13.282877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5b1dffef02'
down_revision: Union[str, Sequence[str], None] = '6932f1d694cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_type', sa.Column('default_procedure_target_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_data_type_default_procedure_target_id_animal_procedure_target'), 'data_type', 'animal_procedure_target', ['default_procedure_target_id'], ['id'])
    op.add_column('data_type_version', sa.Column('default_procedure_target_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_type_version', 'default_procedure_target_id')
    op.drop_constraint(op.f('fk_data_type_default_procedure_target_id_animal_procedure_target'), 'data_type', type_='foreignkey')
    op.drop_column('data_type', 'default_procedure_target_id')
    # ### end Alembic commands ###
