"""make password crypt field longer

Revision ID: 3ccd8ae64ede
Revises: 1e39d2125c99
Create Date: 2026-02-25 17:48:43.028441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccd8ae64ede'
down_revision = '1e39d2125c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_animal_termination_reason_id_termination_reason'), 'termination_reason', ['termination_reason_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_animal_source_id_source'), 'source', ['source_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_animal_species_id_species'), 'species', ['species_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_animal_cage_id_cage'), 'cage', ['cage_id'], ['id'], use_alter=True)

    with op.batch_alter_table('animal_event', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_animal_event_procedure_id_animal_procedure'), 'animal_procedure', ['procedure_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_animal_event_procedure_target_id_animal_procedure_target'), 'animal_procedure_target', ['procedure_target_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_animal_event_animal_id_animal'), 'animal', ['animal_id'], ['id'], use_alter=True)

    with op.batch_alter_table('breeding_pair', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_breeding_pair_female_animal_id_animal'), 'animal', ['female_animal_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_breeding_pair_male_animal_id_animal'), 'animal', ['male_animal_id'], ['id'], use_alter=True)

    with op.batch_alter_table('cage', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_cage_species_id_species'), 'species', ['species_id'], ['id'], use_alter=True)

    with op.batch_alter_table('confocal_image', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_confocal_image_ear_id_ear'), 'ear', ['ear_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_confocal_image_image_type_id_confocal_image_type'), 'confocal_image_type', ['image_type_id'], ['id'], use_alter=True)

    with op.batch_alter_table('ear', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_ear_panel_id_immunolabeling_panel'), 'immunolabeling_panel', ['panel_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_ear_animal_id_animal'), 'animal', ['animal_id'], ['id'], use_alter=True)

    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_litter_breeding_pair_id_breeding_pair'), 'breeding_pair', ['breeding_pair_id'], ['id'], use_alter=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_version', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_litter_breeding_pair_id_breeding_pair'), type_='foreignkey')

    with op.batch_alter_table('ear', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ear_animal_id_animal'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ear_panel_id_immunolabeling_panel'), type_='foreignkey')

    with op.batch_alter_table('confocal_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_confocal_image_image_type_id_confocal_image_type'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_confocal_image_ear_id_ear'), type_='foreignkey')

    with op.batch_alter_table('cage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cage_species_id_species'), type_='foreignkey')

    with op.batch_alter_table('breeding_pair', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_breeding_pair_male_animal_id_animal'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_breeding_pair_female_animal_id_animal'), type_='foreignkey')

    with op.batch_alter_table('animal_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animal_event_animal_id_animal'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_animal_event_procedure_target_id_animal_procedure_target'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_animal_event_procedure_id_animal_procedure'), type_='foreignkey')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animal_cage_id_cage'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_animal_species_id_species'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_animal_source_id_source'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_animal_termination_reason_id_termination_reason'), type_='foreignkey')

    # ### end Alembic commands ###
