"""optional weight

Revision ID: 3d7425aced13
Revises: 0c80048cf9fb
Create Date: 2026-03-03 14:53:58.489126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7425aced13'
down_revision = '0c80048cf9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
