"""make tags nested

Revision ID: 4b07fb56d483
Revises: 6a0cca06bd80
Create Date: 2026-03-11 15:54:25.680694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b07fb56d483'
down_revision = '6a0cca06bd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_event_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_animal_event_tag_parent_id_animal_event_tag'), 'animal_event_tag', ['parent_id'], ['id'])

    with op.batch_alter_table('animal_event_tag_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True))

    with op.batch_alter_table('animal_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_animal_tag_parent_id_animal_tag'), 'animal_tag', ['parent_id'], ['id'])

    with op.batch_alter_table('animal_tag_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_tag_version', schema=None) as batch_op:
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('animal_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animal_tag_parent_id_animal_tag'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('animal_event_tag_version', schema=None) as batch_op:
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('animal_event_tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animal_event_tag_parent_id_animal_event_tag'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
