"""add feed and weight log

Revision ID: 4eb4810800df
Revises: 3ccd8ae64ede
Create Date: 2026-02-26 15:37:06.581752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb4810800df'
down_revision = '3ccd8ae64ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed')),
    sa.UniqueConstraint('name', name=op.f('uq_feed_name'))
    )
    op.create_table('feed_log_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('feed_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_feed_log_version'))
    )
    with op.batch_alter_table('feed_log_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_log_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_log_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_feed_log_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_feed_log_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_log_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('feed_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('weight', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_feed_version'))
    )
    with op.batch_alter_table('feed_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feed_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_feed_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_feed_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feed_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('weight_log_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_weight_log_version'))
    )
    with op.batch_alter_table('weight_log_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_log_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_log_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_weight_log_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_weight_log_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_log_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('feed_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_feed_log_animal_id_animal')),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name=op.f('fk_feed_log_feed_id_feed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_log')),
    sa.UniqueConstraint('animal_id', 'feed_id', 'date', name=op.f('uq_feed_log_animal_id'))
    )
    op.create_table('weight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_weight_log_animal_id_animal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_log')),
    sa.UniqueConstraint('animal_id', 'date', name=op.f('uq_weight_log_animal_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_log')
    op.drop_table('feed_log')
    with op.batch_alter_table('weight_log_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_log_version_transaction_id'))
        batch_op.drop_index('ix_weight_log_version_pk_validity')
        batch_op.drop_index('ix_weight_log_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_weight_log_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_weight_log_version_end_transaction_id'))

    op.drop_table('weight_log_version')
    with op.batch_alter_table('feed_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_version_transaction_id'))
        batch_op.drop_index('ix_feed_version_pk_validity')
        batch_op.drop_index('ix_feed_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_feed_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_feed_version_end_transaction_id'))

    op.drop_table('feed_version')
    with op.batch_alter_table('feed_log_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feed_log_version_transaction_id'))
        batch_op.drop_index('ix_feed_log_version_pk_validity')
        batch_op.drop_index('ix_feed_log_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_feed_log_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_feed_log_version_end_transaction_id'))

    op.drop_table('feed_log_version')
    op.drop_table('feed')
    # ### end Alembic commands ###
