"""add data schema

Revision ID: 6932f1d694cc
Revises: 4b07fb56d483
Create Date: 2026-04-15 20:22:44.155454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6932f1d694cc'
down_revision: Union[str, Sequence[str], None] = '4b07fb56d483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_data_version',
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('data_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('animal_id', 'data_id', 'transaction_id', name=op.f('pk_animal_data_version'))
    )
    op.create_index(op.f('ix_animal_data_version_end_transaction_id'), 'animal_data_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_animal_data_version_operation_type'), 'animal_data_version', ['operation_type'], unique=False)
    op.create_index('ix_animal_data_version_pk_transaction_id', 'animal_data_version', ['animal_id', 'data_id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_animal_data_version_pk_validity', 'animal_data_version', ['animal_id', 'data_id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_animal_data_version_transaction_id'), 'animal_data_version', ['transaction_id'], unique=False)
    op.create_table('data_location_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datatype_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('base_path', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_data_location_version'))
    )
    op.create_index(op.f('ix_data_location_version_end_transaction_id'), 'data_location_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_data_location_version_operation_type'), 'data_location_version', ['operation_type'], unique=False)
    op.create_index('ix_data_location_version_pk_transaction_id', 'data_location_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_data_location_version_pk_validity', 'data_location_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_data_location_version_transaction_id'), 'data_location_version', ['transaction_id'], unique=False)
    op.create_table('data_type_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('filename_regex', sa.String(length=500), autoincrement=False, nullable=True),
    sa.Column('loader_function', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('is_folder', sa.Boolean(), server_default='false', autoincrement=False, nullable=True),
    sa.Column('default_procedure_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_data_type_version'))
    )
    op.create_index(op.f('ix_data_type_version_end_transaction_id'), 'data_type_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_data_type_version_operation_type'), 'data_type_version', ['operation_type'], unique=False)
    op.create_index('ix_data_type_version_pk_transaction_id', 'data_type_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_data_type_version_pk_validity', 'data_type_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_data_type_version_transaction_id'), 'data_type_version', ['transaction_id'], unique=False)
    op.create_table('data_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datatype_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('relative_path', sa.String(length=1024), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_data_version'))
    )
    op.create_index(op.f('ix_data_version_end_transaction_id'), 'data_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_data_version_operation_type'), 'data_version', ['operation_type'], unique=False)
    op.create_index('ix_data_version_pk_transaction_id', 'data_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index('ix_data_version_pk_validity', 'data_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_data_version_transaction_id'), 'data_version', ['transaction_id'], unique=False)
    op.create_table('data_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename_regex', sa.String(length=500), nullable=True),
    sa.Column('loader_function', sa.String(length=200), nullable=True),
    sa.Column('is_folder', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('default_procedure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_procedure_id'], ['animal_procedure.id'], name=op.f('fk_data_type_default_procedure_id_animal_procedure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_type')),
    sa.UniqueConstraint('name', name=op.f('uq_data_type_name'))
    )
    op.create_table('data_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datatype_id', sa.Integer(), nullable=False),
    sa.Column('base_path', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['datatype_id'], ['data_type.id'], name=op.f('fk_data_location_datatype_id_data_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_location'))
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datatype_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['datatype_id'], ['data_type.id'], name=op.f('fk_data_datatype_id_data_type')),
    sa.ForeignKeyConstraint(['event_id'], ['animal_event.id'], name=op.f('fk_data_event_id_animal_event')),
    sa.ForeignKeyConstraint(['location_id'], ['data_location.id'], name=op.f('fk_data_location_id_data_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data')),
    sa.UniqueConstraint('location_id', 'relative_path', name=op.f('uq_data_location_id'))
    )
    op.create_table('animal_data',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_data_animal_id_animal')),
    sa.ForeignKeyConstraint(['data_id'], ['data.id'], name=op.f('fk_animal_data_data_id_data')),
    sa.PrimaryKeyConstraint('animal_id', 'data_id', name=op.f('pk_animal_data'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_data')
    op.drop_table('data')
    op.drop_table('data_location')
    op.drop_table('data_type')
    op.drop_index(op.f('ix_data_version_transaction_id'), table_name='data_version')
    op.drop_index('ix_data_version_pk_validity', table_name='data_version')
    op.drop_index('ix_data_version_pk_transaction_id', table_name='data_version')
    op.drop_index(op.f('ix_data_version_operation_type'), table_name='data_version')
    op.drop_index(op.f('ix_data_version_end_transaction_id'), table_name='data_version')
    op.drop_table('data_version')
    op.drop_index(op.f('ix_data_type_version_transaction_id'), table_name='data_type_version')
    op.drop_index('ix_data_type_version_pk_validity', table_name='data_type_version')
    op.drop_index('ix_data_type_version_pk_transaction_id', table_name='data_type_version')
    op.drop_index(op.f('ix_data_type_version_operation_type'), table_name='data_type_version')
    op.drop_index(op.f('ix_data_type_version_end_transaction_id'), table_name='data_type_version')
    op.drop_table('data_type_version')
    op.drop_index(op.f('ix_data_location_version_transaction_id'), table_name='data_location_version')
    op.drop_index('ix_data_location_version_pk_validity', table_name='data_location_version')
    op.drop_index('ix_data_location_version_pk_transaction_id', table_name='data_location_version')
    op.drop_index(op.f('ix_data_location_version_operation_type'), table_name='data_location_version')
    op.drop_index(op.f('ix_data_location_version_end_transaction_id'), table_name='data_location_version')
    op.drop_table('data_location_version')
    op.drop_index(op.f('ix_animal_data_version_transaction_id'), table_name='animal_data_version')
    op.drop_index('ix_animal_data_version_pk_validity', table_name='animal_data_version')
    op.drop_index('ix_animal_data_version_pk_transaction_id', table_name='animal_data_version')
    op.drop_index(op.f('ix_animal_data_version_operation_type'), table_name='animal_data_version')
    op.drop_index(op.f('ix_animal_data_version_end_transaction_id'), table_name='animal_data_version')
    op.drop_table('animal_data_version')
    # ### end Alembic commands ###
