"""add tags to animal and animalevent

Revision ID: 6a0cca06bd80
Revises: 799ccd2c81b3
Create Date: 2026-03-11 15:10:44.322070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0cca06bd80'
down_revision = '799ccd2c81b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_event_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_event_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_animal_event_tag_name'))
    )
    op.create_table('animal_event_tag_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_animal_event_tag_version'))
    )
    with op.batch_alter_table('animal_event_tag_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_event_tag_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_event_tag_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_event_tag_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_event_tag_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_event_tag_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_event_tags_version',
    sa.Column('animal_event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('animal_event_id', 'tag_id', 'transaction_id', name=op.f('pk_animal_event_tags_version'))
    )
    with op.batch_alter_table('animal_event_tags_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_event_tags_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_event_tags_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_event_tags_version_pk_transaction_id', ['animal_event_id', 'tag_id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_event_tags_version_pk_validity', ['animal_event_id', 'tag_id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_event_tags_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_animal_tag_name'))
    )
    op.create_table('animal_tag_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_animal_tag_version'))
    )
    with op.batch_alter_table('animal_tag_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_tag_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_tag_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_tag_version_pk_transaction_id', ['id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_tag_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_tag_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_tags_version',
    sa.Column('animal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('animal_id', 'tag_id', 'transaction_id', name=op.f('pk_animal_tags_version'))
    )
    with op.batch_alter_table('animal_tags_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_tags_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_tags_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_animal_tags_version_pk_transaction_id', ['animal_id', 'tag_id', sa.literal_column('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_animal_tags_version_pk_validity', ['animal_id', 'tag_id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animal_tags_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('animal_event_tags',
    sa.Column('animal_event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_event_id'], ['animal_event.id'], name=op.f('fk_animal_event_tags_animal_event_id_animal_event')),
    sa.ForeignKeyConstraint(['tag_id'], ['animal_event_tag.id'], name=op.f('fk_animal_event_tags_tag_id_animal_event_tag')),
    sa.PrimaryKeyConstraint('animal_event_id', 'tag_id', name=op.f('pk_animal_event_tags'))
    )
    op.create_table('animal_tags',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_tags_animal_id_animal')),
    sa.ForeignKeyConstraint(['tag_id'], ['animal_tag.id'], name=op.f('fk_animal_tags_tag_id_animal_tag')),
    sa.PrimaryKeyConstraint('animal_id', 'tag_id', name=op.f('pk_animal_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_tags')
    op.drop_table('animal_event_tags')
    with op.batch_alter_table('animal_tags_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_tags_version_transaction_id'))
        batch_op.drop_index('ix_animal_tags_version_pk_validity')
        batch_op.drop_index('ix_animal_tags_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_tags_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_tags_version_end_transaction_id'))

    op.drop_table('animal_tags_version')
    with op.batch_alter_table('animal_tag_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_tag_version_transaction_id'))
        batch_op.drop_index('ix_animal_tag_version_pk_validity')
        batch_op.drop_index('ix_animal_tag_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_tag_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_tag_version_end_transaction_id'))

    op.drop_table('animal_tag_version')
    op.drop_table('animal_tag')
    with op.batch_alter_table('animal_event_tags_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_event_tags_version_transaction_id'))
        batch_op.drop_index('ix_animal_event_tags_version_pk_validity')
        batch_op.drop_index('ix_animal_event_tags_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_event_tags_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_event_tags_version_end_transaction_id'))

    op.drop_table('animal_event_tags_version')
    with op.batch_alter_table('animal_event_tag_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_event_tag_version_transaction_id'))
        batch_op.drop_index('ix_animal_event_tag_version_pk_validity')
        batch_op.drop_index('ix_animal_event_tag_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_animal_event_tag_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_animal_event_tag_version_end_transaction_id'))

    op.drop_table('animal_event_tag_version')
    op.drop_table('animal_event_tag')
    # ### end Alembic commands ###
