"""confocal image frequency should be float

Revision ID: 6c14f2715e47
Revises: 3d7425aced13
Create Date: 2026-03-10 13:56:12.726237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c14f2715e47'
down_revision = '3d7425aced13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confocal_image', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('confocal_image_version', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confocal_image_version', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               autoincrement=False)

    with op.batch_alter_table('confocal_image', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
