"""add nested procedures

Revision ID: 799ccd2c81b3
Revises: 6c14f2715e47
Create Date: 2026-03-11 14:03:56.227392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799ccd2c81b3'
down_revision = '6c14f2715e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_animal_procedure_parent_id_animal_procedure'), 'animal_procedure', ['parent_id'], ['id'])

    with op.batch_alter_table('animal_procedure_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_procedure_version', schema=None) as batch_op:
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('animal_procedure', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_animal_procedure_parent_id_animal_procedure'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
