"""Initial

Revision ID: dbcd5e1d96de
Revises: 
Create Date: 2025-06-26 08:42:03.119715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcd5e1d96de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=100), nullable=False),
    sa.Column('animal_number', sa.Integer(), nullable=False),
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('is_terminated', sa.Boolean(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason_id', sa.Integer(), nullable=True),
    sa.Column('ears_extracted', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cage_id'], ['cage.id'], name=op.f('fk_animal_cage_id_cage')),
    sa.ForeignKeyConstraint(['termination_reason_id'], ['termination_reason.id'], name=op.f('fk_animal_termination_reason_id_termination_reason')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal')),
    sa.UniqueConstraint('custom_id', name=op.f('uq_animal_custom_id'))
    )
    op.create_table('breeding_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_animal_id', sa.Integer(), nullable=False),
    sa.Column('female_animal_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['female_animal_id'], ['animal.id'], name=op.f('fk_breeding_pair_female_animal_id_animal')),
    sa.ForeignKeyConstraint(['male_animal_id'], ['animal.id'], name=op.f('fk_breeding_pair_male_animal_id_animal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breeding_pair'))
    )
    op.create_table('cage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('breeding_pair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breeding_pair_id'], ['breeding_pair.id'], name=op.f('fk_cage_breeding_pair_id_breeding_pair')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_cage_source_id_source')),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_cage_species_id_species')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cage')),
    sa.UniqueConstraint('custom_id', name=op.f('uq_cage_custom_id'))
    )
    op.create_table('immunolabeling_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_immunolabeling_panel')),
    sa.UniqueConstraint('name', name=op.f('uq_immunolabeling_panel_name'))
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedure')),
    sa.UniqueConstraint('name', name=op.f('uq_procedure_name'))
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('name', name=op.f('uq_source_name'))
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species')),
    sa.UniqueConstraint('name', name=op.f('uq_species_name'))
    )
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study')),
    sa.UniqueConstraint('name', name=op.f('uq_study_name'))
    )
    op.create_table('termination_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_termination_reason')),
    sa.UniqueConstraint('reason', name=op.f('uq_termination_reason_reason'))
    )
    op.create_table('animal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_event_animal_id_animal')),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], name=op.f('fk_animal_event_procedure_id_procedure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_event'))
    )
    op.create_table('ear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('cryoprotection_date', sa.Date(), nullable=True),
    sa.Column('dissection_date', sa.Date(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_ear_animal_id_animal')),
    sa.ForeignKeyConstraint(['panel_id'], ['immunolabeling_panel.id'], name=op.f('fk_ear_panel_id_immunolabeling_panel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ear'))
    )
    op.create_table('litter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breeding_pair_id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('pup_count', sa.Integer(), nullable=False),
    sa.Column('is_weaned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['breeding_pair_id'], ['breeding_pair.id'], name=op.f('fk_litter_breeding_pair_id_breeding_pair')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_litter'))
    )
    op.create_table('reagent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dilution', sa.String(length=50), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['immunolabeling_panel.id'], name=op.f('fk_reagent_panel_id_immunolabeling_panel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reagent'))
    )
    op.create_table('study_animals',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_study_animals_animal_id_animal')),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('fk_study_animals_study_id_study')),
    sa.PrimaryKeyConstraint('study_id', 'animal_id', name=op.f('pk_study_animals'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_animals')
    op.drop_table('reagent')
    op.drop_table('litter')
    op.drop_table('ear')
    op.drop_table('animal_event')
    op.drop_table('termination_reason')
    op.drop_table('study')
    op.drop_table('species')
    op.drop_table('source')
    op.drop_table('procedure')
    op.drop_table('immunolabeling_panel')
    op.drop_table('cage')
    op.drop_table('breeding_pair')
    op.drop_table('animal')
    # ### end Alembic commands ###
