"""Simplify immunolabeling panel

Revision ID: dcf6955e7e8c
Revises: efb67d5d3c0d
Create Date: 2026-04-28 15:40:38.693977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf6955e7e8c'
down_revision: Union[str, Sequence[str], None] = 'efb67d5d3c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reagent')
    op.drop_index(op.f('ix_reagent_version_end_transaction_id'), table_name='reagent_version')
    op.drop_index(op.f('ix_reagent_version_operation_type'), table_name='reagent_version')
    op.drop_index(op.f('ix_reagent_version_pk_transaction_id'), table_name='reagent_version')
    op.drop_index(op.f('ix_reagent_version_pk_validity'), table_name='reagent_version')
    op.drop_index(op.f('ix_reagent_version_transaction_id'), table_name='reagent_version')
    op.drop_table('reagent_version')
    op.add_column('immunolabeling_panel', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('immunolabeling_panel_version', sa.Column('description', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('immunolabeling_panel_version', 'description')
    op.drop_column('immunolabeling_panel', 'description')
    op.create_table('reagent_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('panel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_reagent_version'))
    )
    op.create_index(op.f('ix_reagent_version_transaction_id'), 'reagent_version', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_reagent_version_pk_validity'), 'reagent_version', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
    op.create_index(op.f('ix_reagent_version_pk_transaction_id'), 'reagent_version', ['id', sa.literal_column('transaction_id DESC')], unique=False)
    op.create_index(op.f('ix_reagent_version_operation_type'), 'reagent_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_reagent_version_end_transaction_id'), 'reagent_version', ['end_transaction_id'], unique=False)
    op.create_table('reagent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('panel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['immunolabeling_panel.id'], name=op.f('fk_reagent_panel_id_immunolabeling_panel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reagent'))
    )
    # ### end Alembic commands ###
