"""initial

Revision ID: dffc8dfc47e1
Revises: 
Create Date: 2026-02-24 22:33:12.376379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffc8dfc47e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('procedure_target_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_animal_event_animal_id_animal'), use_alter=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['animal_procedure.id'], name=op.f('fk_animal_event_procedure_id_animal_procedure'), use_alter=True),
    sa.ForeignKeyConstraint(['procedure_target_id'], ['animal_procedure_target.id'], name=op.f('fk_animal_event_procedure_target_id_animal_procedure_target'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_event'))
    )
    op.create_table('animal_procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_procedure')),
    sa.UniqueConstraint('name', name=op.f('uq_animal_procedure_name'))
    )
    op.create_table('animal_procedure_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_procedure_target')),
    sa.UniqueConstraint('name', name=op.f('uq_animal_procedure_target_name'))
    )
    op.create_table('breeding_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('male_animal_id', sa.Integer(), nullable=False),
    sa.Column('female_animal_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['female_animal_id'], ['animal.id'], name=op.f('fk_breeding_pair_female_animal_id_animal'), use_alter=True),
    sa.ForeignKeyConstraint(['male_animal_id'], ['animal.id'], name=op.f('fk_breeding_pair_male_animal_id_animal'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breeding_pair')),
    sa.UniqueConstraint('custom_id', name=op.f('uq_breeding_pair_custom_id'))
    )
    op.create_table('cage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_cage_species_id_species'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cage')),
    sa.UniqueConstraint('custom_id', name=op.f('uq_cage_custom_id'))
    )
    op.create_table('confocal_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ear_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('image_type_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ear_id'], ['ear.id'], name=op.f('fk_confocal_image_ear_id_ear'), use_alter=True),
    sa.ForeignKeyConstraint(['image_type_id'], ['confocal_image_type.id'], name=op.f('fk_confocal_image_image_type_id_confocal_image_type'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confocal_image'))
    )
    op.create_table('confocal_image_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confocal_image_type')),
    sa.UniqueConstraint('name', name=op.f('uq_confocal_image_type_name'))
    )
    op.create_table('ear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('cryoprotection_date', sa.Date(), nullable=True),
    sa.Column('dissection_date', sa.Date(), nullable=True),
    sa.Column('immunolabel_date', sa.Date(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_ear_animal_id_animal'), use_alter=True),
    sa.ForeignKeyConstraint(['panel_id'], ['immunolabeling_panel.id'], name=op.f('fk_ear_panel_id_immunolabeling_panel'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ear'))
    )
    op.create_table('immunolabeling_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_immunolabeling_panel')),
    sa.UniqueConstraint('name', name=op.f('uq_immunolabeling_panel_name'))
    )
    op.create_table('litter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breeding_pair_id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('pup_count', sa.Integer(), nullable=False),
    sa.Column('wean_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breeding_pair_id'], ['breeding_pair.id'], name=op.f('fk_litter_breeding_pair_id_breeding_pair'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_litter'))
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('name', name=op.f('uq_source_name'))
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species')),
    sa.UniqueConstraint('name', name=op.f('uq_species_name'))
    )
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study')),
    sa.UniqueConstraint('name', name=op.f('uq_study_name'))
    )
    op.create_table('termination_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_termination_reason')),
    sa.UniqueConstraint('name', name=op.f('uq_termination_reason_name'))
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=100), nullable=True),
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('breeding_pair_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['breeding_pair_id'], ['breeding_pair.id'], name=op.f('fk_animal_breeding_pair_id_breeding_pair')),
    sa.ForeignKeyConstraint(['cage_id'], ['cage.id'], name=op.f('fk_animal_cage_id_cage'), use_alter=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_animal_source_id_source'), use_alter=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_animal_species_id_species'), use_alter=True),
    sa.ForeignKeyConstraint(['termination_reason_id'], ['termination_reason.id'], name=op.f('fk_animal_termination_reason_id_termination_reason'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal')),
    sa.UniqueConstraint('custom_id', name=op.f('uq_animal_custom_id'))
    )
    op.create_table('reagent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['immunolabeling_panel.id'], name=op.f('fk_reagent_panel_id_immunolabeling_panel')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reagent'))
    )
    op.create_table('study_animals',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_study_animals_animal_id_animal')),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name=op.f('fk_study_animals_study_id_study')),
    sa.PrimaryKeyConstraint('study_id', 'animal_id', name=op.f('pk_study_animals'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_animals')
    op.drop_table('reagent')
    op.drop_table('animal')
    op.drop_table('termination_reason')
    op.drop_table('study')
    op.drop_table('species')
    op.drop_table('source')
    op.drop_table('litter')
    op.drop_table('immunolabeling_panel')
    op.drop_table('ear')
    op.drop_table('confocal_image_type')
    op.drop_table('confocal_image')
    op.drop_table('cage')
    op.drop_table('breeding_pair')
    op.drop_table('animal_procedure_target')
    op.drop_table('animal_procedure')
    op.drop_table('animal_event')
    # ### end Alembic commands ###
