"""Add PDF option to datafile

Revision ID: efb67d5d3c0d
Revises: 2a5b1dffef02
Create Date: 2026-04-28 15:31:50.212439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb67d5d3c0d'
down_revision: Union[str, Sequence[str], None] = '2a5b1dffef02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_type', sa.Column('pdf_generator_function', sa.String(length=200), nullable=True))
    op.add_column('data_type_version', sa.Column('pdf_generator_function', sa.String(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_type_version', 'pdf_generator_function')
    op.drop_column('data_type', 'pdf_generator_function')
    # ### end Alembic commands ###
