"""Add custom_id to Animal model

Revision ID: f9c65ff99fb0
Revises: efd3a4c7e66a
Create Date: 2025-06-25 06:36:55.255426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c65ff99fb0'
down_revision = 'efd3a4c7e66a'
branch_labels = None
depends_on = None


#def upgrade():
#    # ### commands auto generated by Alembic - please adjust! ###
#    with op.batch_alter_table('animal', schema=None) as batch_op:
#        batch_op.add_column(sa.Column('custom_id', sa.String(length=100), nullable=False))
#        batch_op.create_unique_constraint(batch_op.f('uq_animal_custom_id'), ['custom_id'])
#
#    # ### end Alembic commands ###

# In your new migration file's upgrade() function:
def upgrade():
    # First, add the column but allow it to be empty temporarily
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_id', sa.String(length=100), nullable=True))

    # Now, populate the new column with the default value for all existing animals
    op.execute("UPDATE animal SET custom_id = cage_id || '-' || animal_number")

    # Finally, make the column NOT NULL now that it's populated
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('custom_id',
               existing_type=sa.String(length=100),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_animal_custom_id'), type_='unique')
        batch_op.drop_column('custom_id')

    # ### end Alembic commands ###
